name: Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      INFURA_IPFS_API_KEY: ${{ secrets.INFURA_IPFS_API_KEY }}
      INFURA_IPFS_API_KEY_SECRET: ${{ secrets.INFURA_IPFS_API_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn compile
      - run: sleep 10
      - run: yarn test
